apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devsecops
  name: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  strategy: {}
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      serviceAccountName: default
      containers:
      - image: {{image}}
        name: devsecops-container
        volumeMounts:
        - mountPath: /tmp
          name: temp-vol
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          runAsUser: 10000
          runAsGroup: 10000
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "750m"
      volumes:
        - name: temp-vol
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devsecops
  name: devsecops-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: devsecops
  type: NodePort